default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

# uncomment for vagrant:
# development:
#   <<: *default
#   database: thingumy_development

# uncomment for docker
development: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: thingumy_test

production:
  <<: *default
  database: thingumy_production
  username: thingumy
  password: <%= ENV['THINGUMY_DATABASE_PASSWORD'] %>
